import esbuild from "esbuild";
import process from "process";

const banner = `/*
WindPost — Obsidian plugin
This file is auto-generated by esbuild. Do not edit directly.
*/`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  jsx: "automatic",
  minify: prod,
  // CSS 当字符串引入用于 juice 内联；HTML 当字符串引入用于 iframe srcDoc
  loader: {
    ".css": "text",
    ".html": "text",
    ".md": "text",
    ".base": "text",
    ".jpg": "dataurl",
  },
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
